server:
  port: 0
spring:
  application:
    name: settle-service
  profiles:
    default: local

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**

#  axonserver:
#    servers: 127.0.0.1:8124
#  serializer:
#    general: xstream
