spring:
  config:
    activate:
      on-profile: secret

  datasource:
    url: jdbc:mysql://13.125.128.164:3306/test
    username: test01
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.20.0.2:8761/eureka/

  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}